name: Docker Build and Run

on:
  push:
    branches:
      - main
      - next-js

jobs:
  build-and-run-next-net5:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Load Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./prod.Dockerfile
          load: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/next-net5:latest
          build-args: |
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
            NEXT_PRIVATE_SUPABASE_SERVICE_KEY=${{ secrets.NEXT_PRIVATE_SUPABASE_SERVICE_KEY }}

  build-and-run-nginx-net5:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Load Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          load: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nginx-net5:latest

  push-to-registry-next-net5:
    needs: build-and-run-next-net5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push next Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./prod.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/next-net5:latest
          build-args: |
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
            NEXT_PRIVATE_SUPABASE_SERVICE_KEY=${{ secrets.NEXT_PRIVATE_SUPABASE_SERVICE_KEY }}

  push-to-registry-nginx-net5:
    needs: build-and-run-nginx-net5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Nginx Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nginx-net5:latest
#  deploy:
#    needs: [push-to-registry-next-net5, push-to-registry-nginx-net5]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Set up Kubectl
#        uses: azure/setup-kubectl@v1
#        with:
#          version: 'v4.0.0'

#      - name: Apply Kubernetes Deployment
#        env:
#          KUBECONFIG_FILE: //$//{{ secrets.KUBECONFIG_FILE }}
#        run: |
#          echo "$KUBECONFIG_FILE" > $HOME/.kube/config
#          kubectl apply -f ./k8s/deployment.yaml
