name: Verify Images
on:
  pull_request:
    branches:
      - main

env:
  REPO: "jjmoner17/next-net5"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.generate.outputs.targets }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List targets
        id: generate
        uses: docker/bake-action/subaction/list-targets@v4

  build:
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      matrix:
        target: ${{ fromJson(needs.prepare.outputs.targets) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master

      # Build Docker images defined in docker-bake.hcl
      - name: Build images
        uses: docker/bake-action@v4.1.0
        with:
          files: |
            ./docker-bake.hcl
          targets: ${{ matrix.target }}
          set: |
            *.platform=linux/amd64
          load: true
          push: false

      # Run the built Docker image to verify it starts correctly
      - name: Run ${{ matrix.target }}
        run: |
          echo "Starting container ${{ matrix.target }}"
          docker run --pull "never" -d --name ${{ matrix.target }}-test "${{ env.REPO }}:${{ matrix.target }}"
          docker logs ${{ matrix.target }}-test

      # Verify that the container is running
      - name: Verify ${{ matrix.target }}
        run: |
          [ $(docker inspect ${{ matrix.target }}-test --format='{{.State.Running}}') = 'true' ]
